### ISSUE TITLE
Audits: Ability to specify groups of properties for property-values audit

### ISSUE THREAD

**Issue by laras126** [ryelle/css-audit#7]
For generating the HTML report, we need a way to specify groups of property-values for the reports. This was accomplished with the CLI table by re-running the command with different values, but for the HTML report, we want to get the audit data for multiple groups at one time. One idea for accomplishing this is to specify an external JSON config file that contains the groups of properties to be audited, and that can be passed to the property-values option to process.

A related need is for a higher level grouping of the output of the --property-values audit. For example, we would want the output of these audits to be under a "Typography" heading in the HTML report:

```
--property-values=font-size
--property-values=line-height
--property-values=font-weight
```

And similarly, these we might want to have under "Spacing":
```
--property-values=padding,padding-top,padding-bottom,padding-left,padding-right
--property-values=margin,margin-top,margin-bottom,margin-left,margin-right
```

This could also be accomplished with the external config approach, but maybe there are other ideas!

**Comment by ryelle** [comment]
@laras126  Do you think this is "done" now that we can group audits like [the typography audit](https://github.com/ryelle/css-audit/blob/e6a881b191371158955cda0a585073be541da540/src/audits/typography.js)?

**Comment by laras126** [comment]
Yes!
